### ISSUE TITLE
drag option is not working for methods

### ISSUE THREAD

**Issue by janibashamd** [f5devcentral/f5-waf-policy-editor#18]
In methods tab if we are using multiple tabs, since it's a list type order matters, also in UI we can reorder methods by using drag option. 
![waf-issue](https://user-images.githubusercontent.com/6093830/131613780-501d6df4-c4bb-4c1b-a71d-b41aad4ce4d5.png)

But observed even if you want to reorder it always go back to initial order only .. ordering doesn't change

**Comment by 464d41** [comment]
It seems policy reference doesn't require method list to be ordered. Maybe we should remove ordering feature from the table.
