### ISSUE TITLE
FileTypes length params validation is not working

### ISSUE THREAD

**Issue by janibashamd** [f5devcentral/f5-waf-policy-editor#25]
Observed in policy reference link for FileTypes tab we have few integer type fields with it's value starting from 0.
But in UI this value throws error as below -

![image](https://user-images.githubusercontent.com/6093830/133045876-861341fb-f650-410d-bc53-75fa9df8eeea.png)
![image](https://user-images.githubusercontent.com/6093830/133045965-3d682571-cdd6-4278-a9dd-cdc4db07c74c.png)

**Comment by janibashamd** [comment]
Also observed if we change values and revert to default values for these params UI always shows error as below -

![image](https://user-images.githubusercontent.com/6093830/133047168-1e5abfc4-0e5b-4970-9ce1-42df22d67f4e.png)

**Comment by 464d41** [comment]
Those fields throw an unrecoverable error for any value.
