### ISSUE TITLE
Drag option not working for links in Open API 

### ISSUE THREAD

**Issue by shubhammishra9** [f5devcentral/f5-waf-policy-editor#27]
Reordering of links in Open API is not working, tested because drag and drop option is active.
Observation: If try to change the order of links in openAPI, again they are falling back to original state when they were added

![Screenshot (5)](https://user-images.githubusercontent.com/90624610/133247042-d45ac206-6a19-4cc5-aea0-ea49c9eb91c7.png)

**Comment by 464d41** [comment]
Order is not significant here. Need to disable draggability.

**Comment by shubhammishra9** [comment]
Observed same behavior in **Signatures/Signature sets** section as well
