### ISSUE TITLE
Duplicate violation name in available options

### ISSUE THREAD

**Issue by shubhammishra9** [f5devcentral/f5-waf-policy-editor#37]
Observed violation name **"Threat Campaign detected"** is used twice in available option list 
![waffler4](https://user-images.githubusercontent.com/90624610/135466754-2b571f9b-179f-4b1f-ba88-c9201d249f87.PNG)

**Comment by 464d41** [comment]
@yoctoserge does violation list come from schema? Is there way to adjust?

**Comment by yoctoserge** [comment]
It comes from my code. Unfortunately no such list in schema. Fixed in: 1b9d2f18201aa916e6939d4ab0c92ad02fe78532
