### ISSUE TITLE
Unable to add IP Address to allow list - Whitelist IPs section

### ISSUE THREAD

**Issue by shubhammishra9** [f5devcentral/f5-waf-policy-editor#42]
Observed error message "**ipMask is not compatible with ipAddress**" while adding IP address and IP mask in Whitelist IPs section.

**Applied policy** 

![viol1](https://user-images.githubusercontent.com/90624610/136395976-d5082744-f4ae-4d1d-8dd5-0a10cf1a00fd.PNG)

**Error Message:**

Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal nginx[2884]: {
Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal nginx[2884]: "completed_successfully" : false,
Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal nginx[2884]: "error_message" : "Failed to import Policy 'myPolicy' from '/etc/app_protect/conf/waf-1633516938513.json': Could not add the Allowlist IP Address '192.168.0.1/24'.  ipMask is not compatible with ipAddress",
Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal nginx[2884]: "error_line_number" : 24
Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal nginx[2884]: }
Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal nginx[2884]: **nginx: [error] APP_PROTECT { "event": "configuration_load_failure", "software_version": "3.639.0", "error_message":"Failed to import Policy 'myPolicy' from '/etc/app_protect/conf/waf-1633516938513.json': Could not add the Allowlist IP Address '192.168.0.1/24'.  ipMask is not compatible with ipAddress","completed_success**
Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal systemd[1]: nginx.service: control process exited, code=exited status=1
Oct 07 13:33:32 ip-172-31-28-230.ap-south-1.compute.internal systemd[1]: Failed to start NGINX Plus - high performance web server.

**Comment by yoctoserge** [comment]
Yes, this is confusing, but the schema specifies that mask should also be in IpV4 format. Like: 255.255.255.0.

**Comment by 464d41** [comment]
@shubhammishra9 In this case network address should be used.
ip - 172.16.0.0 mask - 255.255.0.0 - valid network address containing 2^16 IPs
ip- 172.16.23.233 mask-255.255.255.255 - valid network address containing 1 IP
ip - 172.16.0.1 mask- 255.255.0.0 - It is an IP address out of 172.16.0.0/255.255.255.0 network. In order to block a single IP mask 255.255.255.255 should be used. See above.
ip - 10.10.10.10 mask- 255.0.0.0 - Same as above.
