### ISSUE TITLE
Invalid type conversion in json - Cookie Settings 

### ISSUE THREAD

**Issue by shubhammishra9** [f5devcentral/f5-waf-policy-editor#48]
Observed integer input values are casted to string in json even though as per [doc](https://docs.nginx.com/nginx-app-protect/policy/) allowed values are of type integer(1 to 65536) and for String only 'any' as an input allowed.

**Ref. Doc**
![m1](https://user-images.githubusercontent.com/90624610/136910451-572329ed-97d0-4e41-9c6a-5e25e833c00a.PNG)

**WAFFLER-UI**
![Screenshot (17)](https://user-images.githubusercontent.com/90624610/136910573-72f41314-f36b-45fb-a62c-952524c50a62.png)

**Comment by shubhammishra9** [comment]
We can add one enhancement, increasing/decreasing button with the field element using which 'max cookie header length' value can be modified from min to max allowed values (1-65,536)

**Comment by yoctoserge** [comment]
1. Type conversion is fixed.
2. We cannot make the field as a number with increase/descrease buttons as it may accept the "any" string.
